# Generated by Django 2.2.4 on 2019-11-20 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20191120_1600'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='allstd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
