# Generated by Django 2.1 on 2019-12-18 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_allstd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='allstd',
        ),
    ]
